sudo: required

services:
  - docker

install:
  - docker --version
  - uname -m
  - pip install --user awscli
  - docker network create bantam
  - docker run -d --rm -p 28015:28015 -p 8090:8080 --name rethinkdb --network bantam -v $(pwd -P):/data rethinkdb

script:
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-1 --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t breaks-website:latest .
  - docker run -d --rm
      --network bantam
      --name website
      -e RETHINKDB_HOST=rethinkdb
      -e ENV_INSTAGRAM_USER_ID=${ENV_INSTAGRAM_USER_ID}
      -e ENV_INSTAGRAM_TOKEN=${ENV_INSTAGRAM_TOKEN}
      -p 3000:3000
      breaks-website:latest
  - sleep 15
  - |
    STATUSCODE=$(curl -s -o /dev/null --write-out "%{http_code}" localhost:3000)
    echo "build $TRAVIS_BUILD_NUMBER returned HTTP $STATUSCODE"
    if [[ "$STATUSCODE" != 200 ]]; then
      echo "Test HTTP request to website container failed!  Returned $STATUSCODE"
      docker logs website
      exit 1
    fi
  - docker tag breaks-website:latest 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:latest
  - docker tag breaks-website:latest 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:${TRAVIS_BUILD_NUMBER}
  - docker push 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:latest
  - docker push 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:${TRAVIS_BUILD_NUMBER}

after_success:
  - echo "Build Successful!"
  - docker kill rethinkdb website
  - test $TRAVIS_BRANCH = "master" && ./cicd/deploy.sh $TRAVIS_BUILD_NUMBER
