sudo: required

services:
  - docker

install:
  - docker --version
  - uname -m
  - pip install --user awscli
  - docker network create bantam

script:
  - export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - eval $(aws ecr get-login --region us-east-1 --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t breaks-website:latest .
  - |
    docker run -it breaks-website:latest yarn lint
    RT=$?
    [[ "$RT" = 0 ]] || exit $RT
  - docker run -d
      --network bantam
      --name website
      -e ENV_AWS_REGION=${ENV_AWS_REGION}
      -e ENV_AWS_ACCESS_KEY_ID=${ENV_AWS_ACCESS_KEY_ID}
      -e ENV_AWS_SECRET_ACCESS_KEY=${ENV_AWS_SECRET_ACCESS_KEY}
      -e ENV_INSTAGRAM_USER_ID=${ENV_INSTAGRAM_USER_ID}
      -e ENV_INSTAGRAM_TOKEN=${ENV_INSTAGRAM_TOKEN}
      -e ENV_BOOOKING_SLACK_WEBHOOK_URL=${ENV_BOOOKING_SLACK_WEBHOOK_URL}
      -e ENV_BOOOKING_MAIL_ACCOUNT=${ENV_BOOOKING_MAIL_ACCOUNT}
      -e ENV_BOOOKING_MAIL_PASSWORD=${ENV_BOOOKING_MAIL_PASSWORD}
      -p 3000:3000
      breaks-website:latest
  - sleep $SLEEP_TIME
  - |
    STATUSCODE=$(curl -s -o /dev/null --write-out "%{http_code}" localhost:3000)
    echo "build $TRAVIS_BUILD_NUMBER returned HTTP $STATUSCODE"
    if [[ "$STATUSCODE" != 200 ]]; then
      echo "Test HTTP request to website container failed!  Returned $STATUSCODE"
      docker logs website
      exit 1
    fi
  - docker tag breaks-website:latest 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:latest
  - docker tag breaks-website:latest 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:${TRAVIS_BUILD_NUMBER}
  - docker push 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:latest
  - docker push 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:${TRAVIS_BUILD_NUMBER}

after_success:
  - echo "Build Successful!"
  - |
    if [[ "$TRAVIS_PULL_REQUEST" ]]; then
      if [[ "$TRAVIS_BRANCH" = "master" ]]; then
        ./cicd/deploy.sh $TRAVIS_BUILD_NUMBER website
      elif [[ "$TRAVIS_BRANCH" = "develop" ]]; then
        ./cicd/deploy.sh $TRAVIS_BUILD_NUMBER staging-website
      fi
    fi
